services:
  shared-lib:
    build:
      context: libs/shared
      target: dev
    container_name: presentation-shared-lib-dev
    working_dir: /app/libs/shared
    volumes:
      - type: bind
        source: ./libs/shared
        target: /app/libs/shared
    entrypoint: ["npm", "run", "dev"]
    healthcheck:
      test: ["CMD", "test", "-f", "/app/libs/shared/src/index.ts"]
      interval: 500ms
      retries: 60
      start_period: 1s

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
      target: dev
    container_name: presentation-backend-dev
    working_dir: /app/backend
    volumes:
      - type: bind
        source: ./backend
        target: /app/backend
      - type: bind
        source: ./libs/shared
        target: /app/libs/shared
      - type: volume
        source: backend_node_modules
        target: /app/backend/node_modules
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env
    entrypoint: ["npm", "run", "start:dev"]
    depends_on:
      shared-lib:
        condition: service_healthy

  screenshot-service:
    build:
      context: ./screenshot-service
      dockerfile: Dockerfile
    ports:
      - 5000:3000
    restart: unless-stopped
    shm_size: '1gb'

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
      target: dev
    container_name: presentation-frontend-dev
    working_dir: /app/frontend
    volumes:
      - type: bind
        source: ./frontend
        target: /app/frontend
      - type: bind
        source: ./libs/shared
        target: /app/libs/shared
      - type: volume
        source: frontend_node_modules
        target: /app/frontend/node_modules
    ports:
      - "4200:4200"
    env_file:
      - ./frontend/.env
    environment:
      - CHOKIDAR_USEPOLLING=true
    entrypoint: [ "npm", "run", "start", "--", "--host", "0.0.0.0" ]
    depends_on:
      shared-lib:
        condition: service_healthy

  database:
    image: postgres:15
    container_name: presentation-db-dev
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: presentation
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  backend_node_modules:
  frontend_node_modules:
  pgdata:
